version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: catalog-app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - rabbitmq_catalog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: catalog-elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  rabbitmq_catalog-network:
    external: true
volumes:
  esdata01:
    driver: local